<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>OpenCodeSharp.Acp.Sample</AssemblyName>
    <RootNamespace>OpenCodeSharp.Acp.Sample</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenCodeSharp.Acp\OpenCodeSharp.Acp.csproj" />
  </ItemGroup>
</Project>
